apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: private-ladybug-go
  janus-idp.io/tekton: private-ladybug-go
  backstage.io/kubernetes-id: private-ladybug-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: private-ladybug-go
resources: 
- deployment.yaml
- route.yaml
- service.yaml
