apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: private-ladybug-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: private-ladybug-go 
  name: private-ladybug-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: private-ladybug-go 
